import { mkdir, writeFile } from "node:fs/promises";

const USER = "Finn043";
const token = process.env.GITHUB_TOKEN;
const headers = {
  Accept: "application/vnd.github+json",
  "User-Agent": "Finn043-profile-renderer",
  ...(token ? { Authorization: `Bearer ${token}` } : {}),
};

async function github(path) {
  const res = await fetch(`https://api.github.com${path}`, { headers });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText}: ${path}`);
  return res.json();
}

function n(value) {
  return new Intl.NumberFormat("en").format(value);
}

function top(items, limit) {
  return [...items].sort((a, b) => b[1] - a[1]).slice(0, limit);
}

function esc(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;");
}

const user = await github(`/users/${USER}`);
const repos = (await github(`/users/${USER}/repos?per_page=100&sort=updated`))
  .filter((repo) => !repo.fork);

const totalStars = repos.reduce((sum, repo) => sum + repo.stargazers_count, 0);
const totalForks = repos.reduce((sum, repo) => sum + repo.forks_count, 0);
const languages = new Map();
for (const repo of repos) {
  if (repo.language) languages.set(repo.language, (languages.get(repo.language) ?? 0) + 1);
}

const now = new Date();
const recent = repos.filter((repo) => {
  const pushed = new Date(repo.pushed_at);
  return now - pushed < 1000 * 60 * 60 * 24 * 45;
}).length;

const featured = [
  "tin-luong-portfolio",
  "retail-electronics-analytics",
  "macrobrief",
].map((name) => repos.find((repo) => repo.name === name)).filter(Boolean);

const descriptions = {
  "tin-luong-portfolio": "Personal portfolio site for analytics, BI, and applied AI work.",
  "retail-electronics-analytics": "Python analytics project that transforms raw product review data into product, rating, review-volume, and data-quality insights for BI reporting.",
  macrobrief: "Economic insight tool that fetches macroeconomic time-series data, compares indicators, detects trend shifts, and generates stakeholder-ready briefs.",
};

const iconBase = "https://raw.githubusercontent.com/marwin1991/profile-technology-icons/refs/heads/main/icons";
const technologyGroups = [
  ["Data", [
    ["Python", "python.png"],
    ["Pandas", "pandas.png"],
    ["NumPy", "numpy.png"],
    ["PostgreSQL", "postgresql.png"],
  ]],
  ["Cloud and Engineering", [
    ["Docker", "docker.png"],
    ["GitHub Actions", "githubactions.png"],
    ["Git", "git.png"],
    ["GitHub", "github.png"],
  ]],
  ["Analytics and BI", [
    ["Apache Spark", "apache_spark.png"],
    ["Databricks", "databricks.png"],
  ]],
  ["AI and ML", [
    ["FastAPI", "fastapi.png"],
    ["PyTorch", "pytorch.png"],
    ["Hugging Face", "huggingface.png"],
  ]],
];
const technologyIconHtml = technologyGroups
  .map(([group, icons]) => `| ${group} | ${icons
    .map(([name, file]) => `<img src="${iconBase}/${file}" alt="${name}" title="${name}" width="38" height="38" />`)
    .join(" ")} |`)
  .join("\n");

const languageRows = top(languages, 5)
  .map(([lang, count]) => `| ${lang} | ${count} repo${count === 1 ? "" : "s"} |`)
  .join("\n");

const updated = now.toISOString().slice(0, 10);

const readme = `<!-- generated by scripts/render-profile.mjs; edit the script, not this file -->

<p align="center">
  <img src="./assets/data-orbit.svg" alt="Animated analytics orbit" width="100%" />
</p>

# Tin Luong

Data Scientist and AI Engineer based in Melbourne, Australia.

I build analytics and AI systems that turn raw data, documents, and APIs into validated, stakeholder-ready decisions. My work sits across business intelligence, data pipelines, RAG systems, and Python automation for operational data problems.

<p>
  <a href="https://tin-luong-portfolio.netlify.app"><img alt="Portfolio" src="https://img.shields.io/badge/Portfolio-live-0f766e?style=for-the-badge"></a>
  <a href="https://www.linkedin.com/in/tin-luong"><img alt="LinkedIn" src="https://img.shields.io/badge/LinkedIn-Tin%20Luong-2563eb?style=for-the-badge"></a>
  <a href="mailto:tin.bao.luong@gmail.com"><img alt="Email" src="https://img.shields.io/badge/Email-tin.bao.luong%40gmail.com-7c3aed?style=for-the-badge"></a>
</p>

## Live Metrics

<p>
  <img alt="Public repos" src="https://img.shields.io/badge/Public_repos-${n(user.public_repos)}-111827?style=flat-square">
  <img alt="Portfolio repos" src="https://img.shields.io/badge/Tracked_projects-${n(repos.length)}-111827?style=flat-square">
  <img alt="Recent repos" src="https://img.shields.io/badge/Recently_touched-${n(recent)}-111827?style=flat-square">
  <img alt="Stars" src="https://img.shields.io/badge/Stars-${n(totalStars)}-111827?style=flat-square">
  <img alt="Forks" src="https://img.shields.io/badge/Forks-${n(totalForks)}-111827?style=flat-square">
</p>

<p align="center">
  <img src="./assets/metrics.svg" alt="Dynamic profile metrics" width="100%" />
</p>

## Current Focus

- Business intelligence, KPI reporting, and dashboard-ready analytics marts
- Python and SQL pipelines for cleaning, validating, and transforming data
- RAG and document intelligence for cited, source-grounded answers
- API integrations and typed tool interfaces for analyst workflows
- Applied AI for decision support, not generic demos

## Building Now

${featured.map((repo) => `### [${repo.name}](${repo.html_url})

${repo.description || descriptions[repo.name] || "Portfolio project."}

**Stack:** ${repo.language ?? "Mixed"}  
**Updated:** ${repo.pushed_at.slice(0, 10)}  
`).join("\n")}
### InsightRAG

Business document intelligence system for querying reports, KPI definitions, policies, and analytics specs with hybrid retrieval and cited answers.

**Planned stack:** FastAPI, React, vector search, BM25, reranking, source citations, retrieval evaluation.

## Project Direction

\`\`\`text
Raw data / documents / APIs
  -> ingestion
  -> validation
  -> transformation / retrieval / modeling
  -> BI-ready marts or cited AI answers
  -> stakeholder-facing dashboards and reports
\`\`\`

## Technical Stack

| Area | Technologies |
| --- | --- |
${technologyIconHtml}

**Languages:** Python, SQL, TypeScript  
**Analytics:** Pandas, NumPy, Power BI, Tableau, Looker, Excel  
**Data:** PostgreSQL, BigQuery, Snowflake, DuckDB, dbt  
**AI:** RAG, LangChain, vector search, prompt engineering, evaluation  
**Backend & Tools:** FastAPI, Docker, GitHub Actions, REST APIs

## Experience Themes

- Built KPI dashboards and data models for business teams using Looker and BigQuery
- Developed Python automation for validation, QA, and analytics workflows
- Worked with production data pipelines processing high-volume operational data
- Delivered stakeholder-facing insights across product, customer success, and executive audiences

## Repository Languages

| Language | Count |
| --- | ---: |
${languageRows || "| Updating | 0 |"}

## Contact

- Portfolio: [tin-luong-portfolio.netlify.app](https://tin-luong-portfolio.netlify.app)
- LinkedIn: [linkedin.com/in/tin-luong](https://linkedin.com/in/tin-luong)
- Email: [tin.bao.luong@gmail.com](mailto:tin.bao.luong@gmail.com)

<sub>Last rendered: ${updated}. Metrics refresh daily with GitHub Actions.</sub>
`;

const metricMax = Math.max(...top(languages, 5).map(([, count]) => count), 1);
const bars = top(languages, 5).map(([lang, count], index) => {
  const width = Math.max(42, Math.round((count / metricMax) * 320));
  const y = 88 + index * 38;
  return `<text x="52" y="${y + 18}" fill="#dbeafe" font-size="14" font-family="Arial">${esc(lang)}</text>
  <rect x="160" y="${y}" width="${width}" height="18" rx="9" fill="url(#bar)">
    <animate attributeName="width" from="24" to="${width}" dur="${0.8 + index * 0.12}s" fill="freeze" />
  </rect>
  <text x="${174 + width}" y="${y + 14}" fill="#93c5fd" font-size="12" font-family="Arial">${count}</text>`;
}).join("\n");

const metricsSvg = `<svg xmlns="http://www.w3.org/2000/svg" width="900" height="330" viewBox="0 0 900 330" role="img" aria-label="Dynamic GitHub profile metrics">
  <defs>
    <linearGradient id="bg" x1="0" x2="1" y1="0" y2="1">
      <stop offset="0%" stop-color="#020617"/>
      <stop offset="55%" stop-color="#082f49"/>
      <stop offset="100%" stop-color="#111827"/>
    </linearGradient>
    <linearGradient id="bar" x1="0" x2="1">
      <stop offset="0%" stop-color="#22d3ee"/>
      <stop offset="100%" stop-color="#a78bfa"/>
    </linearGradient>
    <filter id="glow"><feGaussianBlur stdDeviation="4" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter>
  </defs>
  <rect width="900" height="330" rx="18" fill="url(#bg)"/>
  <circle cx="760" cy="76" r="42" fill="none" stroke="#22d3ee" stroke-width="2" opacity=".45" filter="url(#glow)">
    <animate attributeName="r" values="34;52;34" dur="5s" repeatCount="indefinite"/>
  </circle>
  <text x="52" y="48" fill="#f8fafc" font-size="24" font-family="Arial" font-weight="700">GitHub Signal</text>
  <text x="52" y="72" fill="#93c5fd" font-size="13" font-family="Arial">Rendered from live repository metadata on ${updated}</text>
  ${bars}
  <text x="560" y="136" fill="#f8fafc" font-size="42" font-family="Arial" font-weight="700">${n(repos.length)}</text>
  <text x="560" y="160" fill="#93c5fd" font-size="13" font-family="Arial">tracked repos</text>
  <text x="690" y="136" fill="#f8fafc" font-size="42" font-family="Arial" font-weight="700">${n(recent)}</text>
  <text x="690" y="160" fill="#93c5fd" font-size="13" font-family="Arial">recent updates</text>
  <text x="560" y="224" fill="#f8fafc" font-size="42" font-family="Arial" font-weight="700">${n(totalStars)}</text>
  <text x="560" y="248" fill="#93c5fd" font-size="13" font-family="Arial">stars</text>
  <text x="690" y="224" fill="#f8fafc" font-size="42" font-family="Arial" font-weight="700">${n(totalForks)}</text>
  <text x="690" y="248" fill="#93c5fd" font-size="13" font-family="Arial">forks</text>
</svg>
`;

const orbitSvg = `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="360" viewBox="0 0 1200 360" role="img" aria-label="Animated data orbit banner">
  <defs>
    <radialGradient id="core" cx="50%" cy="50%" r="65%">
      <stop offset="0%" stop-color="#22d3ee" stop-opacity=".9"/>
      <stop offset="48%" stop-color="#2563eb" stop-opacity=".34"/>
      <stop offset="100%" stop-color="#020617"/>
    </radialGradient>
    <linearGradient id="line" x1="0" x2="1">
      <stop offset="0%" stop-color="#38bdf8"/>
      <stop offset="50%" stop-color="#a78bfa"/>
      <stop offset="100%" stop-color="#34d399"/>
    </linearGradient>
    <filter id="soft"><feGaussianBlur stdDeviation="6"/></filter>
  </defs>
  <rect width="1200" height="360" fill="#020617"/>
  <circle cx="600" cy="180" r="126" fill="url(#core)" opacity=".72"/>
  <g transform="translate(600 180)" fill="none" stroke="url(#line)" stroke-width="2" opacity=".9">
    <circle r="78" stroke-dasharray="10 12">
      <animateTransform attributeName="transform" type="rotate" from="0" to="360" dur="18s" repeatCount="indefinite"/>
    </circle>
    <circle r="116" stroke-dasharray="24 18">
      <animateTransform attributeName="transform" type="rotate" from="360" to="0" dur="24s" repeatCount="indefinite"/>
    </circle>
    <circle r="154" stroke-dasharray="3 16">
      <animateTransform attributeName="transform" type="rotate" from="0" to="360" dur="34s" repeatCount="indefinite"/>
    </circle>
  </g>
  <g opacity=".52" filter="url(#soft)">
    <circle cx="268" cy="92" r="4" fill="#38bdf8"><animate attributeName="opacity" values=".2;1;.2" dur="3s" repeatCount="indefinite"/></circle>
    <circle cx="884" cy="98" r="5" fill="#a78bfa"><animate attributeName="opacity" values=".2;.9;.2" dur="4s" repeatCount="indefinite"/></circle>
    <circle cx="1010" cy="256" r="4" fill="#34d399"><animate attributeName="opacity" values=".2;1;.2" dur="3.6s" repeatCount="indefinite"/></circle>
    <circle cx="176" cy="268" r="3" fill="#f8fafc"><animate attributeName="opacity" values=".15;.8;.15" dur="5s" repeatCount="indefinite"/></circle>
  </g>
  <path d="M80 276 C260 188 346 232 500 154 S780 90 1120 148" fill="none" stroke="url(#line)" stroke-width="2" opacity=".28">
    <animate attributeName="stroke-dasharray" values="1 18;18 10;1 18" dur="8s" repeatCount="indefinite"/>
  </path>
  <text x="600" y="170" text-anchor="middle" fill="#f8fafc" font-size="42" font-family="Arial" font-weight="700">Tin Luong</text>
  <text x="600" y="205" text-anchor="middle" fill="#bae6fd" font-size="18" font-family="Arial">Data systems, BI marts, and applied AI</text>
</svg>
`;

await mkdir("assets", { recursive: true });
await writeFile("README.md", readme);
await writeFile("assets/metrics.svg", metricsSvg);
await writeFile("assets/data-orbit.svg", orbitSvg);
